Feature/186
aau-giraf/web-api pull request #187
Opened 2021-09-22 12:33 UTC by Molitany

Changed a false to a true in settings

2021-09-23 08:01 UTC, Razhow commented
Du skal merge ind i develop xd

2021-09-23 08:36 UTC, Molitany commented
Burde være rigtigt nu

2021-09-23 08:51 UTC, Razhow approved these changes

2021-09-30 08:31 UTC, Sijmon requested changes
Virker til at den her branch (feature/186) er oprettet ud fra main branchen, og ikke develop branchen, og derfor får vi alle mulige andre ændringer på en masse filer, som virker ret underligt. Branchen burde blive oprettet på ny ud fra develop branchen, og merget ind i develop efter false er ændret til true, i den ene fil som skulle ændres.

2021-10-05 09:17 UTC, closed without merging