Added data for 3 environments and cleaned up the dbinitializer
aau-giraf/web-api pull request #234
Opened 2021-11-16 12:55 UTC by HowToYEET

# Description

I have added the data for the 3 environments so they run with each thier database and changed in both the dbinitializer.cs and startup.cs to match the changes made.

Fixes #\217

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] This change requires a documentation update

# How Has This Been Tested?

NO TEST IT WORKS

- [ ] Test A
- [ ] Test B

**Development Configuration**
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation, if necessary
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, if necessary
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have Acceptance Tested this on an iOS device.

2021-11-16 13:32 UTC, Langbakke approved these changes
Det ser godt ud, men hvordan vil disse ændringer påvirke integration testene? det vil kun tiden vise...

2021-11-19 10:51 UTC, Sijmon requested changes
Ser super fint ud, men har lige skrevet 3 kommentarer som lige skal overvejes

2021-11-19 10:51 UTC, Sijmon commented on GirafRest/Data/roles.json
> +  "SuperUser"
Er rækkefølgen på rollerne ligegyldige? De matcher ikke Models/Enums/GirafRoles.cs, men ved ikke om det har betydning. Index på Citizen starter også på '1'.

2021-11-19 10:51 UTC, Sijmon commented on GirafRest/appsettings.Production.json
> +        "DefaultConnection": "server=172.19.10.30;port=3306;userid=root;password=unknown;database=giraf-prod;Allow User Variables=True"
Har hørt om grupper på forrige semestre som er blevet angrebet af github bots, som leder efter github repositories som gemmer deres database ConnectionStrings online, og hvis de finder den, automatisk sletter alt i hele databasen, og kræver penge for at give data retur. Ved ikke om det bliver et problem ved os, da jeg mindes at vores github repository kun kan ses af dem der er med i organisationen, men er ikke sikker. Uanset hvad, plejer det ikke at være en god ide at gemme den online

2021-11-19 10:51 UTC, Sijmon commented on GirafRest/Data/DB_data.prod.json
> +      "Password": "password"
Er det her kodeordet til de users som kommer til at ligge i databasen? Giver det mening at gemme det i repositoriet på github?

2021-11-22 11:37 UTC, HowToYEET commented on GirafRest/Data/roles.json
> +  "SuperUser"
ingen konflikt her :D er testet og databasen sortere dem selv når de kommer ind

2021-11-22 11:53 UTC, Sijmon approved these changes

2021-11-22 12:00 UTC, merged

2021-12-08 13:52 UTC, Sijmon reviewed
@HowToYEET ved ikke om det er dig, eller en anden fra jeres gruppe?

2021-12-08 13:52 UTC, Sijmon commented on GirafRest/Data/DBInitializer.cs
> -            CreatePictograms(pictogramCount);
Dette er lidt skyld i at der aldrig bliver genereret lokale piktogram billeder :#
Selvom at kaldet er rykket ned til linje, genererer den ikke nogle, da den ikke tjekker for om selve "pictograms" folderen er lavet, men i stedet tjekker for om der er piktogrammer i databasen (hvilket der sagtens kan være, selvom billederne ikke er genereret i filsystemet på computeren)