Fix for StatusController integration test
aau-giraf/web-api pull request #294
Opened 2022-11-10 12:46 UTC by MadeByMM

Added authentication tokens using the methods found in the AccountControllerTest

# Description
This fixes the integration tests for StatusController failing, by including authorization tokens in each test. The method for retrieving the tokens was taken from AccountControllerTest.

Fixes #\<283>

## Type of change
*Delete unchecked boxes (only for Type of change)*

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Three different devices have run the tests and all have passed.

**Development Configuration**
*Type "flutter --version" and "dart --version" in your CMD to check versions.*

* Flutter version: 2.0.5
* Dart version: 2.12.3

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas, if necessary
- [ ] I have made corresponding changes to the documentation, if necessary
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, if necessary
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have Acceptance Tested this on an iOS device
- [ ] I have Acceptance Tested this on an Android device

2022-11-18 07:30 UTC, J2KJonas approved these changes

2022-11-18 10:33 UTC, AOsnes requested changes
version-info endpoint test does not pass on linux. Please fix before merging

2022-11-18 13:29 UTC, J2KJonas commented
After approving it seems that I had some problems with connecting to the db, after that got fixed then some rather interesting errors seem to make the test to fail / not being recognised at all 
![image](https://user-images.githubusercontent.com/75009936/202716048-cc7c9c8a-f538-4016-a85e-1aaf6a487445.png)

2022-11-22 10:28 UTC, MadeByMM commented
Since there are errors that we cannot recreate on our end, we are closing this pull request for now.

2022-11-22 10:28 UTC, closed without merging