Settings for weekplanner feature 857
aau-giraf/web-api pull request #303
Opened 2022-11-18 10:11 UTC by Taoshix

# Description

Added Number of Actitivies to Display, Show Only Actitivies and Show Settings for Citizens to the web api and the settings table in the database to be used in the weekplanner and api client

Fixes related to #857 in weekplanner

## Type of change
*Delete unchecked boxes (only for Type of change)*

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

This has been tested by having the api client and weekplaner run tests that make requests to the web api to both get and insert data into the database. Specifically inputted and extracted data regarding the newly created attributes.

**Development Configuration**
*Type "flutter --version" and "dart --version" in your CMD to check versions.*

* Flutter version: 2.0.5
* Dart version: 2.12.3

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas, if necessary
- [ ] I have made corresponding changes to the documentation, if necessary
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works, if necessary
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have Acceptance Tested this on an iOS device
- [x] I have Acceptance Tested this on an Android device

2022-11-18 10:56 UTC, Jaffenheimer requested changes
AddedShowOnlyActivitiesAndNrOfActivitiesToDisplayToSettingsTable.Designer.cs, AddedShowOnlyActivitiesAndNrOfActivitiesToDisplayToSettingsTable.cs og AddedShowSettingsForCitizenToSettingsTable.Designer.cs er efter min mening alt alt alt for lange klasse navne og bør ændres til noget mere kort og præcist. 

Resterende kommentarer til specifik kode kan ses i @NikolajKrogh's review.

2022-11-18 10:59 UTC, NikolajKrogh commented on GirafRest/Migrations/20221101082038_AddedShowOnlyActivitiesAndNrOfActivitiesToDisplayToSettingsTable.cs
> +#nullable disable
Hvorfor har i tilføjet #nullable disable?

2022-11-18 11:09 UTC, Jaffenheimer commented
Har i testet dette også? Synes ikke jeg kan se at i har tilføjet nogle tests, bliver det i har lavet om allerede testet i forvejen?

2022-11-21 11:03 UTC, Taoshix commented on GirafRest/Migrations/20221101082038_AddedShowOnlyActivitiesAndNrOfActivitiesToDisplayToSettingsTable.cs
> +#nullable disable
Dette er auto generated fra migration tool

2022-11-22 09:48 UTC, Jaffenheimer approved these changes
This looks good to me now

2022-11-22 11:33 UTC, AOsnes requested changes
Looks good except for the comment left

2022-11-22 11:33 UTC, AOsnes commented on GirafRest/appsettings.Development.json
> +        "DefaultConnection": "server=localhost;port=3306;userid=root;password=Giraf123;database=giraf;Allow User Variables=True"
Remove localhost from commmit

2022-11-22 12:03 UTC, Taoshix commented on GirafRest/appsettings.Development.json
> +        "DefaultConnection": "server=localhost;port=3306;userid=root;password=Giraf123;database=giraf;Allow User Variables=True"
Removed localhost

2022-11-22 12:18 UTC, AOsnes commented
TestUserCanCheckMultipleSettings integration test fails when running locally.

2022-11-23 07:34 UTC, Taoshix commented
> TestUserCanCheckMultipleSettings integration test fails when running locally.

drop the giraf database then run `dotnet-ef database update`

There was a merge conflict in the last commit

2022-11-23 11:53 UTC, AOsnes approved these changes
lgtm

2022-11-23 12:07 UTC, merged